[macros.install__arch]
	prefix = ["yaourt", "-S"]


[macros.install__osx]
	prefix = ["brew", "install"]

[tasks.bootstrap_common]
	cmds = [
		["bash", "${PWD}/tasks_bootstrap_common.sh"]
	]

[tasks.bootstrap__arch]
	deps = ["bootstrap_common"]
	cmds = [
		["@install", "nvm", "nix"],
		["bash", "${PWD}/tasks_bootstrap__${HM_VARIANT}.sh"]
	]

[tasks.bootstrap__osx]
	deps = ["bootstrap_common"]
	cmds = [
		["bash", "${PWD}/tasks_bootstrap__${HM_VARIANT}.sh"]
	]

[tasks.default]
	cmds = [
		["echo", "Please choose a variant (osx, arch)."]
	]

[tasks.default__arch]
	links = [
		[".bashrc", "common/.bashrc"],
		[".bash_profile", "common/.bash_profile"],
		[".zshenv", "common/.zshenv"],
		[".xol_profile_common", "common/.xol_profile_common"],
		[".xol_profile", "${HM_VARIANT}/.xol_profile"],
		[".Xresources", "${HM_VARIANT}/.Xresources"],
		[".zimrc", "common/.zimrc"],
		[".config/sublime-text-3/Packages/User", "common/.config/Packages/User"],
		[".config/bspwm", "${HM_VARIANT}/.config/bspwm"],
		[".config/sxhkd", "${HM_VARIANT}/.config/sxhkd"]
	]

[tasks.default__osx]
	links = [
		[".bashrc", "common/.bashrc"],
		[".bash_profile", "common/.bash_profile"],
		[".zshenv", "common/.zshenv"],
		[".xol_profile_common", "common/.xol_profile_common"],
		[".xol_profile", "${HM_VARIANT}/.xol_profile"],
		[".zimrc", "common/.zimrc"],
		["Library/Application Support/Sublime Text 3/Packages/User", "common/.config/Packages/User"]
	]
