[macros.install__arch]
	prefix = ["yaourt", "-S"]


[macros.install__osx]
	prefix = ["brew", "install"]

[tasks.bootstrap_common]
	cmds = [
		["bash", "${PWD}/tasks_bootstrap_common.sh"]
	]

[tasks.bootstrap__arch]
	deps = ["bootstrap_common"]
	cmds = [
		["@install",
			 "nvm",
			 "nix",
			 "i3-gaps",
			 "neovim"
		],
		["bash", "${PWD}/tasks_bootstrap__${HM_VARIANT}.sh"]
	]

[tasks.bootstrap__osx]
	deps = ["bootstrap_common"]
	cmds = [
		["bash", "${PWD}/tasks_bootstrap__${HM_VARIANT}.sh"]
	]

[tasks.default]
	cmds = [
		["echo", "Please choose a variant (osx, arch)."]
	]

[tasks.default__arch]
	links = [
		[".bashrc", "common/.bashrc"],
		[".bash_profile", "common/.bash_profile"],
		[".zshenv", "common/.zshenv"],
		[".xol_profile_common", "common/.xol_profile_common"],
		[".xol_profile", "${HM_VARIANT}/.xol_profile"],
		[".Xresources", "${HM_VARIANT}/.Xresources"],
		[".xinitrc", "${HM_VARIANT}/.xinitrc"],
		[".zimrc", "common/.zimrc"],
		[".colors.conf", "${HM_VARIANT}/.colors.conf"],
		[".i3blocks.conf", "${HM_VARIANT}/.i3blocks.conf"],
		[".config/nvim", "${HM_VARIANT}/.config/nvim"],
		[".config/termite", "${HM_VARIANT}/.config/termite"],
		[".config/sublime-text-3/Packages/User", "common/.config/Packages/User"],
		[".config/fontconfig", "${HM_VARIANT}/.config/fontconfig"],
		[".config/i3", "${HM_VARIANT}/.config/i3"],
		[".config/cava", "${HM_VARIANT}/.config/cava"],
        [".config/yabar", "${HM_VARIANT}/.config/yabar"],
		[".config/sway", "${HM_VARIANT}/.config/sway"],
		[".config/gsimplecal", "${HM_VARIANT}/.config/gsimplecal"],
		[".config/compton.conf", "${HM_VARIANT}/.config/compton.conf"],
		["scripts", "${HM_VARIANT}/scripts"],
	]

[tasks.default__osx]
	links = [
		[".bashrc", "common/.bashrc"],
		[".bash_profile", "common/.bash_profile"],
		[".zshenv", "common/.zshenv"],
		[".xol_profile_common", "common/.xol_profile_common"],
		[".xol_profile", "${HM_VARIANT}/.xol_profile"],
		[".zimrc", "common/.zimrc"],
		[".config/nvim", "${HM_VARIANT}/.config/nvim"],
		["Library/Application Support/Sublime Text 3/Packages/User", "common/.config/Packages/User"]
	]
