[macros.install__arch]
	prefix = ["yaourt", "-S"]


[macros.install__osx]
	prefix = ["brew", "install"]

[tasks.bootstrap_common]
	cmds = [
		["./dotfiles/tasks_bootstrap_common.sh"]
	]

[tasks.bootstrap__arch]
	deps = ["bootstrap_common"]
	cmds = [
		["@install", "nvm", "nix"],
		["./dotfiles/tasks_bootstrap__${HM_VARIANT}.sh"]
	]

[tasks.bootstrap__osx]
	deps = ["bootstrap_common"]
	cmds = [
		["./dotfiles/tasks_bootstrap__${HM_VARIANT}.sh"]
	]

[tasks.default]
	links = [
		[".bashrc", "common/.bashrc"],
		[".bash_profile", "common/.bash_profile"],
		[".zshenv", "common/.zshenv"],

		[".xol_profile_common", "common/.xol_profile_common"],
		[".xol_profile", "${HM_VARIANT}/.xol_profile"],

		[".Xresources", "${HM_VARIANT}/.Xresources"],

		[".zimrc", "common/.zimrc"],
	]