[macros.install__arch]
	prefix = ["yaourt", "-S"]


[macros.install__osx]
	prefix = ["brew", "install"]

[tasks.bootstrap]
	cmds = [
		["pwd"],
		["./dotfiles/tasks_bootstrap_cmd1.sh"]
	]

[tasks.default]
	links = [
		[".bashrc", "common/.bashrc"],
		[".bash_profile", "common/.bash_profile"],
		[".zshenv", "common/.zshenv"],

		[".xol_profile_common", "common/.xol_profile_common"],
		[".xol_profile", "${HM_VARIANT}/.xol_profile"],

		[".Xresources", "${HM_VARIANT}/.Xresources"],

		[".zimrc", "common/.zimrc"],
	]