[[tool]]
name = 'eza'
check = "command -v 'eza'"

[tool.install]
macos = ''

[tool.install.linux]
default = 'sudo apt install eza'
arch = "yay -S eza"

[[tool]]
name = 'tig'
check = "command -v 'tig'"

[tool.install]
macos = ''

[tool.install.linux]
default = 'sudo apt install tig'
arch = "yay -S tig"
