[[tool]]
name = 'eza'
check = "command -v 'eza'"

[tool.install]
macos = ''

[tool.install.linux]
arch = 'yay -S eza'
default = 'sudo apt install eza'

[[tool]]
name = 'shellcheck'
check = "command -v 'shellcheck'"

[tool.install]
macos = ''

[tool.install.linux]
arch = 'yay -S shellcheck'
default = ''

[[tool]]
name = 'tig'
check = "command -v 'tig'"

[tool.install]
macos = ''

[tool.install.linux]
arch = 'yay -S tig'
default = 'sudo apt install tig'
